/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.gui;

/**
 *
 * @author Faychan
 */
public class otransfer extends javax.swing.JFrame {
    int mo = new balance().mo;
    /**
     * Creates new form otransfer
     */
    public otransfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        ah = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        tf9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick your Doctor", "DR. Farras Yassar", "DR. Anisa Putri", "DR. Atika Nur Shabrina" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(340, 50, 140, 30);

        ah.setBackground(new java.awt.Color(102, 102, 255));
        ah.setToolTipText("");
        ah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ah.setName(""); // NOI18N
        ah.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Identity"));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel2.setText("Waktu Praktik");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 340, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel3.setText("Alamat");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 60, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel4.setText("Umur");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 100, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 140, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel6.setText("Golongan Darah");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 180, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel7.setText("Nama");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 20, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel8.setText("Status");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 220, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel9.setText("Kewarganegaraan");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 260, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel10.setText("Spesialis");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 300, 120, 30);

        tf2.setEditable(false);
        tf2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jPanel2.add(tf2);
        tf2.setBounds(180, 60, 220, 30);

        tf1.setEditable(false);
        tf1.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel2.add(tf1);
        tf1.setBounds(180, 20, 220, 30);

        tf3.setEditable(false);
        tf3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jPanel2.add(tf3);
        tf3.setBounds(180, 100, 220, 30);

        tf4.setEditable(false);
        tf4.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jPanel2.add(tf4);
        tf4.setBounds(180, 140, 220, 30);

        tf5.setEditable(false);
        tf5.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jPanel2.add(tf5);
        tf5.setBounds(180, 180, 220, 30);

        tf6.setEditable(false);
        tf6.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jPanel2.add(tf6);
        tf6.setBounds(180, 220, 220, 30);

        tf7.setEditable(false);
        tf7.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        jPanel2.add(tf7);
        tf7.setBounds(180, 260, 220, 30);

        tf8.setEditable(false);
        tf8.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jPanel2.add(tf8);
        tf8.setBounds(180, 300, 220, 30);

        tf9.setEditable(false);
        tf9.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jPanel2.add(tf9);
        tf9.setBounds(180, 340, 220, 30);

        ah.add(jPanel2);
        jPanel2.setBounds(40, 100, 420, 400);

        jLabel12.setFont(new java.awt.Font("Pristina", 0, 36)); // NOI18N
        jLabel12.setText("DOCTOR ELECTION");
        ah.add(jLabel12);
        jLabel12.setBounds(30, 30, 360, 40);

        getContentPane().add(ah);
        ah.setBounds(0, 0, 500, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Farah Noriffat (XIRPL1/13)
        if(jComboBox1.getSelectedItem().equals("DR. Farras Yassar")){
            tf1.setText("DR. Farras Yassar ");
            tf2.setText("Jl. Surabaya 16, Malang");
            tf3.setText("20 Tahun");
            tf4.setText("Laki-Laki");
            tf5.setText("A");
            tf6.setText("Belum Menikah ");
            tf7.setText("Indonesia");
            tf8.setText("Dokter Umum");
            tf9.setText(" Pagi (07.00-15.00)");
        }
        else if(jComboBox1.getSelectedItem().equals("DR. Anisa Putri")){
            tf1.setText("DR. Anisa Putri");
            tf2.setText("Jl. Veteran 3, Malang");
            tf3.setText("20 Tahun");
            tf4.setText("Perempuan");
            tf5.setText("O");
            tf6.setText("Belum Menikah");
            tf7.setText("Indonesia");
            tf8.setText("Dokter Gigi");
            tf9.setText(" Sore (16.00-22.00)");
    }//GEN-LAST:event_jComboBox1ActionPerformed
    }
    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(otransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(otransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(otransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(otransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new otransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    // End of variables declaration//GEN-END:variables
}
