/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Faychan
 */
public class widrawal extends javax.swing.JFrame {
   int mo = new balance().mo;
   int saldo;

    /**
     * Creates new form widrawal
     */
    public widrawal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        b7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        b8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Soria", 1, 18)); // NOI18N
        jLabel3.setText("CASH WIDRAWAL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 0, 150, 60);

        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setText(">");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(361, 80, 60, 30);

        b3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b3.setText(">");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(360, 150, 60, 30);

        b5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b5.setText("<");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(10, 80, 60, 30);

        b6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b6.setText("<");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(100, 300, 60, 30);

        jLabel5.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel5.setText("Other Amounts");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 300, 110, 30);

        jLabel6.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel6.setText("Rp200.000");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 80, 70, 30);

        jLabel7.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel7.setText("Rp1.000.0000");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 80, 110, 30);

        jLabel8.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel8.setText("Rp300.000");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 150, 70, 30);

        b7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b7.setText("<");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(10, 140, 60, 30);

        jLabel9.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel9.setText("Rp1.500.000");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 140, 100, 30);

        b4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b4.setText(">");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(360, 210, 60, 30);

        jLabel10.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel10.setText("Rp500.000");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(290, 210, 70, 30);

        jLabel11.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel11.setText("Rp2.500.000");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 200, 100, 30);

        b8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b8.setText("<");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(10, 200, 60, 30);

        setSize(new java.awt.Dimension(483, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        int t = 200000;
        
        if(t>mo)
                JOptionPane.showMessageDialog(null, 
                    "Balance amount is not enough\n"
                            + "please deposit",
                    "Transaction Failed",0);
        else if(t<100000)
                JOptionPane.showMessageDialog(null, 
                    "Minimum Widrawal is Rp100.000",
                    "Transaction Failed",0);
        else {
                mo-=t;
                new balance().mo = this.mo;
                JOptionPane.showMessageDialog(null, "Balance Amount: Rp."+mo);
                if(mo<=100000)
                    JOptionPane.showMessageDialog(null, "Minimum Balance Amount must be Rp. 100.000,00"+
                            "Do deposit soon to avoid account closure","CAUTION",2);
            }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        int t = 300000;
        
        if(t>mo)
                JOptionPane.showMessageDialog(null, 
                    "Balance amount is not enough\n"
                            + "please deposit",
                    "Transaction Failed",0);
        else if(t<100000)
                JOptionPane.showMessageDialog(null, 
                    "Minimum Widrawal is Rp100.000",
                    "Transaction Failed",0);
        else {
                mo-=t;
                new balance().mo = this.mo;
                JOptionPane.showMessageDialog(null, "Balance Amount: Rp."+mo);
                if(mo<=100000)
                    JOptionPane.showMessageDialog(null, "Minimum Balance Amount must be Rp100.000,00"+
                            "Do deposit soon to avoid account closure","CAUTION",2);
            }
    }//GEN-LAST:event_b3ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        int t = 1000000;
        
        if(t>mo)
                JOptionPane.showMessageDialog(null, 
                    "Balance amount is not enough\n"
                            + "please deposit",
                    "Transaction Failed",0);
        else if(t<100000)
                JOptionPane.showMessageDialog(null, 
                    "Minimum Widrawal is Rp100.000",
                    "Transaction Failed",0);
        else {
                mo-=t; 
                new balance().mo = this.mo;
                JOptionPane.showMessageDialog(null, "Balance Amount: Rp."+mo);
                if(mo<=100000)
                    JOptionPane.showMessageDialog(null, "Minimum Balance Amount must be Rp100.000,00"+
                            "Do deposit soon to avoid account closure","CAUTION",2);
            }
    }//GEN-LAST:event_b5ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        int t = 1500000;
        
        if(t>mo)
                JOptionPane.showMessageDialog(null, 
                    "Balance amount is not enough\n"
                            + "please deposit",
                    "Transaction Failed",0);
        else if(t<100000)
                JOptionPane.showMessageDialog(null, 
                    "Minimum Widrawal is Rp100.000",
                    "Transaction Failed",0);
        else {
                mo-=t; 
                new balance().mo = this.mo;
                JOptionPane.showMessageDialog(null, "Balance Amount: Rp."+mo);
                if(mo<=100000)
                    JOptionPane.showMessageDialog(null, "Minimum Balance Amount must be Rp100.000,00"+
                            "Do deposit soon to avoid account closure","CAUTION",2);
            }
    }//GEN-LAST:event_b7ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        c_widrawal fer = new c_widrawal();
            dispose();
        fer.setVisible(true);
    }//GEN-LAST:event_b6ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
         int t = 500000;
        
        if(t>mo)
                JOptionPane.showMessageDialog(null, 
                    "Balance amount is not enough\n"
                            + "please deposit",
                    "Transaction Failed",0);
        else if(t<100000)
                JOptionPane.showMessageDialog(null, 
                    "Minimum Widrawal is Rp100.000",
                    "Transaction Failed",0);
        else {
                mo-=t; 
                new balance().mo = this.mo;
                JOptionPane.showMessageDialog(null, "Balance Amount: Rp."+mo);
                if(mo<=100000)
                    JOptionPane.showMessageDialog(null, "Minimum Balance Amount must be Rp100.000,00"+
                            "Do deposit soon to avoid account closure","CAUTION",2);
            }
    }//GEN-LAST:event_b4ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
         int t = 2500000;
        
        if(t>mo)
                JOptionPane.showMessageDialog(null, 
                    "Balance amount is not enough\n"
                            + "please deposit",
                    "Transaction Failed",0);
        else if(t<100000)
                JOptionPane.showMessageDialog(null, 
                    "Minimum Widrawal is Rp100.000",
                    "Transaction Failed",0);
        else {
                mo-=t; 
                new balance().mo = this.mo;
                JOptionPane.showMessageDialog(null, "Balance Amount: Rp."+mo);
                if(mo<=100000)
                    JOptionPane.showMessageDialog(null, "Minimum Balance Amount must be Rp100.000,00"+
                            "Do deposit soon to avoid account closure","CAUTION",2);
            }
    }//GEN-LAST:event_b8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(widrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(widrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(widrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(widrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new widrawal().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
